spring:
  application:
    name: "leasingservice-api"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-proud-leaf-a51y702n-pooler.us-east-2.aws.neon.tech/leasingservicedb?user=wesleybritovlk&password=pOEY4f8qbtVk&sslmode=require
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    web: "info"
    org.springframework.web: "info"
    org.hibernate: "info"

